// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moive_finder.Data_Layer;

#nullable disable

namespace Moive_finder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240701063244_SeedMovieTable2")]
    partial class SeedMovieTable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moive_finder.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Genre = "Action",
                            Name = "x-men"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Genre = "Action",
                            Name = "My Hero Academia"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Genre = "Documentary",
                            Name = "The wall"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
